## Nginx config
kind: ConfigMap
apiVersion: v1
metadata:
  name: vxe-journals-nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      client_header_timeout 3000;
      client_body_timeout 3000;
      client_max_body_size 100M;
      
      include /etc/nginx/mime.types;
      server {
        listen 80;
        listen [::]:80;

        add_header Content-Security-Policy 'upgrade-insecure-requests';

        root /var/www/html/build;
        index index.html;

        if (!-e $request_filename) {
          rewrite ^.*$ /index.html last;
        }
      }
    }

---

## App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vxe-journals-deployment
  labels:
    name: vxe-journals-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      name: vxe-journals-pod
  template:
    metadata:
      name: vxe-journals-pod
      labels:
        name: vxe-journals-pod
    spec:
      volumes:
        - name: app-files
          emptyDir: {}
    
        - name: vxe-journals-nginx-config-volume
          configMap:
            name: vxe-journals-nginx-config
    
      containers:
        - image: dgstagingregistry.azurecr.io/vxe-journals:#{Build.BuildNumber}#
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
            - name: vxe-journals-nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: app-files
              mountPath: /var/www/html
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html && cd /var/www/html && npm install && npm run build"]
    
          ports:
          - containerPort: 80

---

## Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/force-ssl-redirect: "false" 
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: vxe-journals-ingress
spec:
  tls:
    - hosts:
        - vxe-journals.stg-lanstad.com
      secretName: tls-secret-vxe-journals
  rules:
    - host: vxe-journals.stg-lanstad.com
      http:
        paths:
          - backend:
              serviceName: vxe-journals-service
              servicePort: 80

---

## App service
apiVersion: v1
kind: Service
metadata:
  name: vxe-journals-service
spec:
  selector:
    name: vxe-journals-pod
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP