version: '3.2'
services:
  lst-www:
    build: nginx
    container_name: vxe-journals-www
    working_dir: /vxe-journals-service
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '../vxe-journals-service:/vxe-journals-service'
    ports:
      - '8181:80'
      - '3131:3000'
